// src/lib/components/nav/Header.tsx
import type { ReactNode } from 'react';
import type { Analytics } from '~/lib/analytics.functions';
import { DynamicHeader } from '~/lib/components/nav/DynamicHeader';
import { HighFiveCounter } from '~/lib/components/nav/HighFiveCounter';
import { LiveClock } from '~/lib/components/nav/LiveClock';
import { formatNumber, formatOrdinal } from '~/lib/utils';

type HeaderProps = {
	analytics: Analytics;
	highFiveCount: number;
};

export function Header({ analytics, highFiveCount }: HeaderProps) {
	return (
		<header className="bevel-button title-bar-gradient box-border flex h-20 shrink-0 gap-1 overflow-hidden p-1 pr-2">
			<div className="box-border grid h-full w-[45%] shrink-0 grid-cols-3 gap-3 p-3">
				<HeaderWidget videoSrc="/gifs/globe.webm">
					<span className="text-blue-700">
						You are the{' '}
						<span className="blink font-bold text-orange-700">
							{formatOrdinal(analytics.totalViews)}
						</span>{' '}
						visitor!
					</span>
				</HeaderWidget>
				<HeaderWidget videoSrc="/gifs/skull.webm">
					<span className="text-red-700">
						<span className="font-bold text-red-600">{formatNumber(analytics.badActors)}</span>{' '}
						bots/scrapers
					</span>
				</HeaderWidget>
				<LiveClock />
			</div>

			<div className="bevel-inset my-1 flex w-[25%] shrink-0 flex-col gap-1 overflow-hidden bg-[#c0c0c0] p-1">
				<div className="flex min-h-0 flex-1 gap-1">
					<div className="min-w-0 flex-1 overflow-hidden">
						<HighFiveCounter initialCount={highFiveCount} />
					</div>
					<div className="min-w-0 flex-1 overflow-hidden">
						<video
							autoPlay
							loop
							muted
							playsInline
							aria-hidden="true"
							src="/gifs/rainbow.webm"
							className="h-full w-full object-cover"
						/>
					</div>
				</div>
				<div className="min-h-0 flex-1 overflow-hidden">
					<video
						autoPlay
						loop
						muted
						playsInline
						aria-hidden="true"
						src="/gifs/under_construction.webm"
						className="h-full w-full object-fill"
					/>
				</div>
			</div>

			<div className="bevel-inset my-1 w-[30%] shrink-0 overflow-hidden">
				<DynamicHeader />
			</div>
		</header>
	);
}

type HeaderWidgetProps = {
	videoSrc: string;
	children: ReactNode;
};

function HeaderWidget({ videoSrc, children }: HeaderWidgetProps) {
	return (
		<div className="bevel-inset flex h-full items-center gap-2 bg-white px-2">
			<video
				autoPlay
				loop
				muted
				playsInline
				aria-hidden="true"
				src={videoSrc}
				className="h-5 w-5 shrink-0"
			/>
			<div className="text-xs">{children}</div>
		</div>
	);
}

// src/lib/components/nav/header.svelte
<script lang="ts">
	import type { Analytics } from '$lib/schema.js';
	import DynamicHeader from '../DynamicHeader.svelte';
	import HighFiveCounter from '../HighFiveCounter.svelte';
	import UnderConstructionGif from '../UnderConstructionGif.svelte';
	import HeaderWidgets from './header-widgets.svelte';

	export let analytics: Analytics;
</script>

<header
	class="bevel-button box-border h-32 overflow-hidden bg-gradient-to-r from-black to-gray-900 text-white"
>
	<table class="h-full w-full table-fixed border-collapse">
		<colgroup>
			<col style="width: 28.57%" />
			<col style="width: 28.57%" />
			<col style="width: 42.86%" />
		</colgroup>
		<tbody>
			<tr class="h-full">
				<td class="h-full p-0 align-top">
					<HeaderWidgets {analytics} />
				</td>
				<td class="h-full p-0 align-top">
					<table class="h-full w-full table-fixed border-collapse" style="table-layout: fixed; height: 100%;">
						<colgroup>
							<col style="width: 50%" />
							<col style="width: 50%" />
						</colgroup>
						<tbody>
							<tr style="height: 25%;">
								<td class="p-0 align-top overflow-hidden" style="height: 25%; max-height: 32px;">
									<div class="w-full overflow-hidden" style="height: 32px;">
										<HighFiveCounter />
									</div>
								</td>
								<td class="overflow-hidden p-0" style="height: 25%; max-height: 32px;">
									<div class="flex w-full items-center" style="height: 32px;">
										<video autoplay loop muted playsinline aria-hidden="true" src="/gifs/rainbow.webm" class="w-full" style="height: 32px; object-fit: cover;"></video>
									</div>
								</td>
							</tr>
							<tr style="height: 25%">
								<td class="overflow-hidden p-0">
									<div class="flex h-full w-full items-center justify-center gap-1 bg-black">
										<video autoplay loop muted playsinline aria-hidden="true" src="/gifs/hot_1.webm" class="max-h-full max-w-[25%] object-contain"></video>
										<video autoplay loop muted playsinline aria-hidden="true" src="/gifs/hot_2.webm" class="max-h-full max-w-[25%] object-contain"></video>
										<video autoplay loop muted playsinline aria-hidden="true" src="/gifs/hot_3.webm" class="max-h-full max-w-[25%] object-contain"></video>
										<video autoplay loop muted playsinline aria-hidden="true" src="/gifs/hot_4.webm" class="max-h-full max-w-[25%] object-contain"></video>
									</div>
								</td>

								<td class="h-0 overflow-hidden p-0"> </td>
							</tr>
							<tr style="height: 25%">
								<td class="overflow-hidden p-0"> </td>
								<td class="h-0 overflow-hidden p-0"> </td>
							</tr>
							<tr style="height: 25%">
								<td colspan="2" class="p-0 align-top">
									<div class="h-full w-full overflow-hidden">
										<UnderConstructionGif />
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td class="h-full p-0 align-top">
					<DynamicHeader />
				</td>
			</tr>
		</tbody>
	</table>
</header>
