// src/lib/components/HighFiveCounter.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let highFiveCount = 0;
	let loading = false;
	let remaining = 5;
	let resetTimer: NodeJS.Timeout | null = null;

	onMount(async () => {
		try {
			const response = await fetch('/api/high-five');
			const data = await response.json();
			highFiveCount = data.count;
		} catch (error) {
			console.error('Failed to load high five count:', error);
		}
	});

	async function giveHighFive() {
		if (loading || remaining <= 0) return;

		loading = true;

		const previousCount = highFiveCount;
		highFiveCount++;

		try {
			const response = await fetch('/api/high-five', {
				method: 'POST'
			});

			const data = await response.json();

			if (!response.ok) {
				if (response.status === 429) {
					remaining = 0;
					if (resetTimer) clearInterval(resetTimer);
					let timeLeft = data.resetTime;
					resetTimer = setInterval(() => {
						timeLeft--;
						if (timeLeft <= 0) {
							remaining = 5;
							if (resetTimer) clearInterval(resetTimer);
						}
					}, 1000);
				}
				highFiveCount = previousCount;
			} else {
				highFiveCount = data.count;
				remaining = data.remaining;
			}
		} catch (error) {
			console.error('Failed to give high five:', error);
			highFiveCount = previousCount;
		} finally {
			loading = false;
		}
	}
</script>

<div
	class="relative flex h-full w-full cursor-pointer items-center bg-yellow-300 px-6"
	style="background-image: url('/gifs/flame-border.webp'); background-size: 100% 100%; background-repeat: no-repeat;"
	on:click={giveHighFive}
	on:keydown={(e) => e.key === 'Enter' && giveHighFive()}
	role="button"
	tabindex="0"
	title="Give a high five!"
>
	<div class="flex w-full flex-row justify-between">
		<div class="text-xs font-bold text-red-900">High Fives:</div>
		<div class="text-xs font-bold text-red-900">{highFiveCount.toLocaleString()}</div>
	</div>
</div>

// src/lib/components/nav/HighFiveCounter.tsx
import { useState } from 'react';
import { giveHighFive } from '~/lib/highFive.functions';
import { formatNumber } from '~/lib/utils';

export function HighFiveCounter({ initialCount }: { initialCount: number }) {
	const [count, setCount] = useState(initialCount);
	const [isPending, setIsPending] = useState(false);

	async function handleHighFive() {
		setIsPending(true);
		setCount((previousCount) => previousCount + 1);
		try {
			const response = await giveHighFive();
			if (response.result === 'counted') setCount(response.count);
			else setCount((previousCount) => previousCount - 1);
		} catch (error) {
			console.error('highfive: failed to give a high five', error);
			setCount((previousCount) => previousCount - 1);
		} finally {
			setIsPending(false);
		}
	}

	return (
		<button
			type="button"
			onClick={handleHighFive}
			disabled={isPending}
			title="Give a high five!"
			aria-label={`Give a high five! ${formatNumber(count)} so far`}
			className="relative flex h-full w-full items-center bg-yellow-300 bg-[url('/gifs/flame-border.webp')] bg-size-[100%_100%] bg-no-repeat px-6 disabled:cursor-wait"
		>
			<span className="flex w-full flex-row justify-between text-xs font-bold text-red-900">
				<span>High Fives:</span>
				<span>{formatNumber(count)}</span>
			</span>
		</button>
	);
}
