// legacy-svelte/lib/components/nav/LiveClock.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';

	let time = '';
	let date = '';
	let interval: ReturnType<typeof setInterval>;

	function tick() {
		const now = new Date();
		time = now.toLocaleTimeString('en-NZ', {
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit',
			hour12: false
		});
		date = now
			.toLocaleDateString('en-NZ', { weekday: 'short', day: '2-digit', month: 'short' })
			.toUpperCase();
	}

	onMount(() => {
		tick();
		interval = setInterval(tick, 1000);
	});

	onDestroy(() => clearInterval(interval));
</script>

<div class="bevel-inset flex h-full flex-col items-center justify-center bg-black px-2">
	<span class="font-mono text-sm leading-none font-bold text-green-400">{time}</span>
	<span class="font-mono text-[10px] leading-none text-green-600">{date}</span>
</div>

// src/lib/components/nav/LiveClock.tsx
import { format } from 'date-fns';
import { useNow } from '~/lib/hooks/useNow';
import { mapNullish } from '~/lib/utils';

export function LiveClock() {
	const now = useNow(1000);

	return (
		<div className="bevel-inset flex h-full flex-col items-center justify-center bg-black px-2">
			<span className="font-mono text-sm leading-none font-bold text-green-400">
				{mapNullish(now, (date) => format(date, 'HH:mm:ss'))}
			</span>
			<span className="font-mono text-[10px] leading-none text-green-600">
				{mapNullish(now, (date) => format(date, 'EEE dd MMM').toUpperCase())}
			</span>
		</div>
	);
}
