// src/lib/components/Guestbook.tsx
import { useForm, useStore } from '@tanstack/react-form';
import { Link, useRouter, useRouterState } from '@tanstack/react-router';
import { useState } from 'react';
import { Input } from '~/lib/components/Input';
import { RetroDiv } from '~/lib/components/RetroDiv';
import {
	addGuestbookEntry,
	type GuestbookEntry,
	type GuestbookPage
} from '~/lib/guestbook.functions';
import { guestbookSchema } from '~/lib/schema';
import { cn, formatNumber, formatNzDay } from '~/lib/utils';

const guestbookErrorMessages = {
	RATE_LIMIT: 'Too many messages... perhaps an email might get your point across better?',
	SUBMIT_FAILED: 'Something broke while signing the guestbook. Give it another go in a minute.',
	TOO_LONG_NAME: 'Thats not your name buddy',
	TOO_LONG_MESSAGE: 'What are you writing? An essay? Pls stop',
	TOO_LONG_LOCATION: 'Are you by chance welsh?',
	SWEAR_WORDS_NAME:
		'Maybe people call you those words in private but I wont let you call yourself that. Just looking out for you bud',
	SWEAR_WORDS_MESSAGE:
		'Cmon man the website might not look professional but theres no need for all that',
	SWEAR_WORDS_LOCATION: 'Surely not.'
} as const;

type GuestbookErrorCode = keyof typeof guestbookErrorMessages;
type SubmitErrorCode = Extract<GuestbookErrorCode, 'RATE_LIMIT' | 'SUBMIT_FAILED'>;

function isGuestbookErrorCode(value: string): value is GuestbookErrorCode {
	return Object.hasOwn(guestbookErrorMessages, value);
}

const guestbookColumns = [
	{ label: 'Name', width: 'w-[20%]' },
	{ label: 'Date', width: 'w-[10%]' },
	{ label: 'Location', width: 'w-[20%]' },
	{ label: 'Message', width: 'w-[50%]' }
];

const emptyGuestbookForm = { name: '', location: '', message: '' };

type GuestbookFormValues = typeof emptyGuestbookForm;

export type GuestbookLoadState = { status: 'loaded'; page: GuestbookPage } | { status: 'failed' };

export function Guestbook({ guestbook }: { guestbook: GuestbookLoadState }) {
	return (
		<RetroDiv>
			<table className="-ml-[2px] w-[calc(100%+4px)] table-auto border-collapse bg-yellow-100">
				<thead>
					<tr>
						<td colSpan={4} className="bg-gradient-to-r from-green-600 to-blue-600 p-2 text-center">
							<span className="retro-text-shadow text-lg font-bold text-white">
								Sign My Guestbook :3
							</span>
						</td>
					</tr>
					<tr className="bg-yellow-100">
						<td colSpan={4} className="p-3 text-center">
							<GuestbookForm />
						</td>
					</tr>
					<tr>
						{guestbookColumns.map((column) => (
							<th
								key={column.label}
								className={cn(
									'bevel-button bg-purple-200 p-2 font-bold text-purple-800',
									column.width
								)}
							>
								{column.label}
							</th>
						))}
					</tr>
				</thead>
				{guestbook.status === 'loaded' ? (
					<GuestbookEntries page={guestbook.page} />
				) : (
					<tbody>
						<tr>
							<td colSpan={4} className="p-4 text-center text-red-700">
								The guestbook couldn't be loaded right now. Try refreshing in a minute.
							</td>
						</tr>
					</tbody>
				)}
			</table>
		</RetroDiv>
	);
}

function GuestbookEntries({ page }: { page: GuestbookPage }) {
	const isLoadingPage = useRouterState({ select: (state) => state.isLoading });
	const hasPreviousPage = page.page > 1;
	const hasNextPage = page.page < page.totalPages;

	return (
		<>
			<tbody className={cn(isLoadingPage && 'opacity-50')}>
				{page.entries.length === 0 ? (
					<tr>
						<td colSpan={4} className="p-4 text-center text-gray-500">
							{page.totalCount === 0
								? 'No entries yet. Be the first to sign!'
								: 'No entries on this page.'}
						</td>
					</tr>
				) : (
					page.entries.map((entry) => <GuestbookEntryRow key={entry.id} entry={entry} />)
				)}
			</tbody>
			<tfoot>
				<tr>
					<td colSpan={4} className="bg-gradient-to-r from-purple-300 to-pink-300 p-2">
						<div className="flex items-center justify-between">
							<span className="text-sm font-bold text-purple-800">
								Total Entries: {formatNumber(page.totalCount)}
								{page.entries.length > 0 && (
									<>
										{' '}
										| <span className="blink">New!</span>
									</>
								)}
							</span>

							{page.totalPages > 1 && (
								<div className="flex items-center gap-2">
									<GuestbookPageLink page={page.page - 1} disabled={!hasPreviousPage}>
										‹ Prev
									</GuestbookPageLink>
									<span className="px-2 text-xs font-bold text-purple-800">
										{page.page} / {page.totalPages}
									</span>
									<GuestbookPageLink page={page.page + 1} disabled={!hasNextPage}>
										Next ›
									</GuestbookPageLink>
								</div>
							)}
						</div>
					</td>
				</tr>
			</tfoot>
		</>
	);
}

type GuestbookPageLinkProps = {
	page: number;
	disabled: boolean;
	children: string;
};

function GuestbookPageLink({ page, disabled, children }: GuestbookPageLinkProps) {
	return (
		<Link
			to="/"
			search={{ page }}
			disabled={disabled}
			resetScroll={false}
			className={cn(
				'bevel-button bg-white px-2 py-1 text-xs font-bold',
				disabled && 'cursor-not-allowed opacity-50'
			)}
		>
			{children}
		</Link>
	);
}

function GuestbookEntryRow({ entry }: { entry: GuestbookEntry }) {
	return (
		<tr className="border-b border-gray-200">
			<td className="bevel-inset bg-yellow-50 p-2 text-sm font-semibold">{entry.name}</td>
			<td className="bevel-inset bg-yellow-50 p-2 text-sm">{formatNzDay(entry.createdAt)}</td>
			<td className="bevel-inset bg-yellow-50 p-2 text-sm">{entry.location || '-'}</td>
			<td className="bevel-inset bg-yellow-50 p-2 text-sm">{entry.message}</td>
		</tr>
	);
}

function GuestbookForm() {
	const router = useRouter();
	const [submitError, setSubmitError] = useState<SubmitErrorCode | null>(null);

	const form = useForm({
		defaultValues: emptyGuestbookForm,
		validators: { onSubmit: guestbookSchema },
		onSubmit: async ({ value, formApi }) => {
			setSubmitError(null);
			try {
				const response = await addGuestbookEntry({ data: value });
				if (response.result === 'rateLimited') {
					setSubmitError('RATE_LIMIT');
					return;
				}
				formApi.reset();
				await router.invalidate({ filter: (match) => match.routeId === '/' });
			} catch (error) {
				console.error('guestbook: failed to add entry', error);
				setSubmitError('SUBMIT_FAILED');
			}
		}
	});

	const values = useStore(form.store, (state) => state.values);
	const isSubmitting = useStore(form.store, (state) => state.isSubmitting);
	const validationErrorCode = getValidationErrorCode(values);
	const errorCode = submitError ?? validationErrorCode;

	return (
		<div className="bevel-button inline-block bg-gray-200 p-3">
			<form
				className="flex flex-wrap items-center gap-2"
				onSubmit={(event) => {
					event.preventDefault();
					void form.handleSubmit();
				}}
			>
				<form.Field name="name">
					{(field) => (
						<label className="flex items-center gap-2">
							<span className="text-sm font-bold">Name:</span>
							<Input
								type="text"
								className="px-2 py-1 text-sm"
								placeholder="Your name"
								required
								value={field.state.value}
								onChange={field.handleChange}
								onBlur={field.handleBlur}
							/>
						</label>
					)}
				</form.Field>
				<form.Field name="location">
					{(field) => (
						<label className="flex items-center gap-2">
							<span className="text-sm font-bold">Location:</span>
							<Input
								type="text"
								className="px-2 py-1 text-sm"
								placeholder="Optional"
								value={field.state.value}
								onChange={field.handleChange}
								onBlur={field.handleBlur}
							/>
						</label>
					)}
				</form.Field>
				<form.Field name="message">
					{(field) => (
						<label className="flex flex-1 items-center gap-2">
							<span className="text-sm font-bold">Message:</span>
							<Input
								type="text"
								className="flex-1 px-2 py-1 text-sm"
								placeholder="Leave a message!"
								required
								value={field.state.value}
								onChange={field.handleChange}
								onBlur={field.handleBlur}
							/>
						</label>
					)}
				</form.Field>
				<button
					type="submit"
					disabled={isSubmitting}
					className="bevel-button bg-blue-500 px-3 py-1 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"
				>
					{isSubmitting ? 'Signing...' : 'Sign!'}
				</button>
			</form>
			{errorCode && (
				<div className="bevel-inset mt-3 border-2 p-3 text-center text-sm" role="alert">
					{guestbookErrorMessages[errorCode]}
				</div>
			)}
		</div>
	);
}

function getValidationErrorCode(values: GuestbookFormValues) {
	const result = guestbookSchema.safeParse(values);
	if (result.success) return null;
	return result.error.issues.map((issue) => issue.message).find(isGuestbookErrorCode) ?? null;
}

// src/lib/components/Guestbook.svelte
<script lang="ts">
	import RetroDiv from './RetroDiv.svelte';
	import { superForm } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { guestbookSchema } from '../../routes/schema.js';
	import { goto, invalidateAll } from '$app/navigation';
	import { page } from '$app/stores';
	import { derived } from 'svelte/store';

	export let data;

	interface GuestbookEntry {
		id: number;
		name: string;
		message: string;
		location?: string;
		createdAt: Date;
	}

	interface PaginationInfo {
		page: number;
		limit: number;
		totalCount: number;
		totalPages: number;
		hasNext: boolean;
		hasPrev: boolean;
	}

	let serverMessage = '';

	const { form, enhance, submitting, message } = superForm(data.form, {
		validators: zodClient(guestbookSchema),
		resetForm: true,
		onResult: async ({ result }) => {
			if (result.type === 'failure' && result.data?.message) {
				serverMessage = result.data.message;
			} else if (result.type === 'success') {
				serverMessage = '';
				await invalidateAll();
			}
		}
	});

	$: entries = data.entries as GuestbookEntry[];
	$: pagination = data.pagination as PaginationInfo;

	type ErrorType =
		| 'RATE_LIMIT'
		| 'TOO_LONG_NAME'
		| 'TOO_LONG_MESSAGE'
		| 'TOO_LONG_LOCATION'
		| 'SWEAR_WORDS_NAME'
		| 'SWEAR_WORDS_MESSAGE'
		| 'SWEAR_WORDS_LOCATION';

	const errorMessages: Record<ErrorType, string> = {
		RATE_LIMIT: 'Too many messages... perhaps an email might get your point across better?',
		TOO_LONG_NAME: 'Thats not your name buddy',
		TOO_LONG_MESSAGE: 'What are you writing? An essay? Pls stop',
		TOO_LONG_LOCATION: 'Are you by chance welsh?',
		SWEAR_WORDS_NAME:
			'Maybe people call you those words in private but I wont let you call yourself that. Just looking out for you bud',
		SWEAR_WORDS_MESSAGE:
			'Cmon man the website might not look professional but theres no need for all that',
		SWEAR_WORDS_LOCATION: 'Surely not.'
	};

	const clientValidation = derived(form, ($formData) => {
		if (!$formData.name && !$formData.message && !$formData.location) return null;

		try {
			guestbookSchema.parse($formData);
			return null;
		} catch (error: any) {
			if (error.issues) {
				for (const issue of error.issues) {
					if (issue.message === 'TOO_LONG_NAME') return 'TOO_LONG_NAME';
					if (issue.message === 'TOO_LONG_MESSAGE') return 'TOO_LONG_MESSAGE';
					if (issue.message === 'TOO_LONG_LOCATION') return 'TOO_LONG_LOCATION';
					if (issue.message === 'SWEAR_WORDS_NAME') return 'SWEAR_WORDS_NAME';
					if (issue.message === 'SWEAR_WORDS_MESSAGE') return 'SWEAR_WORDS_MESSAGE';
					if (issue.message === 'SWEAR_WORDS_LOCATION') return 'SWEAR_WORDS_LOCATION';
				}
			}
			return null;
		}
	});

	$: currentError = (() => {
		if (serverMessage && serverMessage.includes('You have reached the maximum number of guestbook entries')) {
			return 'RATE_LIMIT';
		}
		if (serverMessage) {
			if (serverMessage.includes('too long')) {
				if (serverMessage.includes('name')) return 'TOO_LONG_NAME';
				if (serverMessage.includes('message')) return 'TOO_LONG_MESSAGE';
				if (serverMessage.includes('location')) return 'TOO_LONG_LOCATION';
			}
			return null;
		}
		return $clientValidation as ErrorType | null;
	})();

	function formatDate(date: Date): string {
		return new Date(date).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric'
		});
	}

	function changePage(newPage: number) {
		if (newPage >= 1 && newPage <= pagination.totalPages) {
			const url = new URL($page.url);
			url.searchParams.set('page', newPage.toString());
			goto(url.toString());
		}
	}
</script>

<RetroDiv width="w-full">
	<table class="w-full table-auto border-collapse bg-yellow-100">
		<thead>
			<tr>
				<td colspan="4" class="bg-gradient-to-r from-green-600 to-blue-600 p-2 text-center">
					<span class="retro-text-shadow text-lg font-bold text-white">Sign My Guestbook :3</span>
				</td>
			</tr>
			<tr class="bg-yellow-100">
				<td colspan="4" class="p-3 text-center">
					<div class="bevel-button inline-block bg-gray-200 p-3">
						<form
							class="flex flex-wrap items-center gap-2"
							method="POST"
							action="?/addEntry"
							use:enhance
						>
							<span class="text-sm font-bold">Name:</span>
							<input
								type="text"
								name="name"
								class="bevel-inset px-2 py-1 text-sm"
								placeholder="Your name"
								bind:value={$form.name}
								required
							/>
							<span class="text-sm font-bold">Location:</span>
							<input
								type="text"
								name="location"
								class="bevel-inset px-2 py-1 text-sm"
								placeholder="Optional"
								bind:value={$form.location}
							/>
							<span class="text-sm font-bold">Message:</span>
							<input
								type="text"
								name="message"
								class="bevel-inset flex-1 px-2 py-1 text-sm"
								placeholder="Leave a message!"
								bind:value={$form.message}
								required
							/>
							<button
								type="submit"
								class="bevel-button bg-blue-500 px-3 py-1 text-sm font-bold text-white {$submitting
									? 'cursor-not-allowed opacity-50'
									: ''}"
								disabled={$submitting}
							>
								{$submitting ? 'Signing...' : 'Sign!'}
							</button>
						</form>
						{#if currentError}
							{@const errorInfo = errorMessages[currentError]}
							<div class="bevel-inset mt-3 border-2 p-3 text-sm">
								<div class="flex items-center gap-2 text-center">
									<span class="text-center">{errorInfo}</span>
								</div>
							</div>
						{/if}
					</div>
				</td>
			</tr>
			<tr>
				<th class="bevel-button bg-purple-200 p-2 font-bold text-purple-800">Name</th>
				<th class="bevel-button bg-purple-200 p-2 font-bold text-purple-800">Date</th>
				<th class="bevel-button bg-purple-200 p-2 font-bold text-purple-800">Location</th>
				<th class="bevel-button bg-purple-200 p-2 font-bold text-purple-800">Message</th>
			</tr>
		</thead>
		<tbody>
			{#if entries.length === 0}
				<tr>
					<td colspan="4" class="p-4 text-center text-gray-500"
						>No entries yet. Be the first to sign!</td
					>
				</tr>
			{:else}
				{#each entries as entry (entry.id)}
					<tr class="border-b border-gray-200">
						<td class="bevel-inset bg-yellow-50 p-2 text-sm font-semibold">{entry.name}</td>
						<td class="bevel-inset bg-yellow-50 p-2 text-sm">{formatDate(entry.createdAt)}</td>
						<td class="bevel-inset bg-yellow-50 p-2 text-sm">{entry.location || '-'}</td>
						<td class="bevel-inset bg-yellow-50 p-2 text-sm">{entry.message}</td>
					</tr>
				{/each}
			{/if}
		</tbody>
		<tfoot>
			<tr>
				<td colspan="4" class="bg-gradient-to-r from-purple-300 to-pink-300 p-2">
					<div class="flex items-center justify-between">
						<span class="text-sm font-bold text-purple-800">
							Total Entries: {pagination.totalCount}
							{#if entries.length > 0}| <span class="blink">New!</span>{/if}
						</span>

						{#if pagination.totalPages > 1}
							<div class="flex items-center gap-2">
								<button
									class="bevel-button bg-white px-2 py-1 text-xs font-bold {!pagination.hasPrev
										? 'cursor-not-allowed opacity-50'
										: ''}"
									disabled={!pagination.hasPrev}
									on:click={() => changePage(pagination.page - 1)}
								>
									‹ Prev
								</button>
								<span class="px-2 text-xs font-bold text-purple-800">
									{pagination.page} / {pagination.totalPages}
								</span>
								<button
									class="bevel-button bg-white px-2 py-1 text-xs font-bold {!pagination.hasNext
										? 'cursor-not-allowed opacity-50'
										: ''}"
									disabled={!pagination.hasNext}
									on:click={() => changePage(pagination.page + 1)}
								>
									Next ›
								</button>
							</div>
						{/if}
					</div>
				</td>
			</tr>
		</tfoot>
	</table>
</RetroDiv>
