// src/lib/components/RetroDiv.svelte
<script lang="ts">
	import BevelInset from './ui/BevelInset.svelte';

	export let width: string = 'w-56';
	export let className: string = '';
</script>

<BevelInset
	class="flex {width} flex-col overflow-hidden bg-[#d4d4d4] font-[Verdana] text-[13px] leading-tight text-black {className}"
>
	<slot />
</BevelInset>

// src/lib/components/RetroDiv.tsx
import type { ReactNode } from 'react';
import { cn } from '~/lib/utils';

type RetroDivProps = {
	className?: string;
	children: ReactNode;
};

export function RetroDiv({ className, children }: RetroDivProps) {
	return (
		<div
			className={cn(
				'bevel-inset flex w-full flex-col overflow-hidden bg-[#d4d4d4] font-[Verdana] text-[13px] leading-tight text-black',
				className
			)}
		>
			{children}
		</div>
	);
}
