// src/lib/components/UsesCard.svelte
<script lang="ts">
	import RetroDiv from '$lib/components/RetroDiv.svelte';
	import type { Section } from '$lib/types';

	let { section }: { section: Section } = $props();
</script>

<RetroDiv width="w-full" className="p-3">
	<h2 class="mb-3 flex items-center gap-2 font-mono text-xs font-bold text-blue-700">
		<svelte:component this={section.Icon} size={14} />
		{section.title}
	</h2>
	<div class="flex flex-col gap-1">
		{#each section.items as item (item.label)}
			<div class="flex gap-2 border-b border-gray-200 pb-1 last:border-0 last:pb-0">
				<span class="w-28 shrink-0 font-mono text-xs font-bold text-gray-500">{item.label}</span>
				<span class="min-w-0 font-mono text-xs text-gray-800">{item.value}</span>
			</div>
		{/each}
	</div>
</RetroDiv>

// src/lib/components/UsesCard.tsx
import { Window } from '~/lib/components/ui/Window';
import type { Section } from '~/lib/types';

export function UsesCard({ section }: { section: Section }) {
	return (
		<Window className="p-3">
			<h2 className="mb-3 flex items-center gap-2 font-mono text-xs font-bold text-blue-700">
				<section.Icon size={14} aria-hidden="true" />
				{section.title}
			</h2>
			<div className="flex flex-col gap-1">
				{section.items.map((item) => (
					<div
						key={item.label}
						className="flex gap-2 border-b border-gray-200 pb-1 last:border-0 last:pb-0"
					>
						<span className="w-28 shrink-0 font-mono text-xs font-bold text-gray-500">
							{item.label}
						</span>
						<span className="min-w-0 font-mono text-xs text-gray-800">{item.value}</span>
					</div>
				))}
			</div>
		</Window>
	);
}
